import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'

interface ElectronCookie {
  name: string
  value: string
  domain: string
  path: string
  secure: boolean
  httpOnly: boolean
  expirationDate?: number
  sameSite?: string
}

export function convertToNetscape(cookies: ElectronCookie[]): string {
  const lines: string[] = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by Video Downloader. Edit at your own risk.',
    ''
  ]

  for (const cookie of cookies) {
    const domain = cookie.domain
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const cookiePath = cookie.path || '/'
    const secure = cookie.secure ? 'TRUE' : 'FALSE'
    const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : '0'
    lines.push([domain, flag, cookiePath, secure, expires, cookie.name, cookie.value].join('\t'))
  }

  return lines.join('\n') + '\n'
}

export async function writeTempCookieFile(cookies: ElectronCookie[]): Promise<string> {
  const netscape = convertToNetscape(cookies)
  const tmpPath = path.join(os.tmpdir(), `vd-cookies-${Date.now()}.txt`)
  await fs.promises.writeFile(tmpPath, netscape, 'utf-8')
  return tmpPath
}

export async function deleteTempCookieFile(filePath: string): Promise<void> {
  try {
    await fs.promises.unlink(filePath)
  } catch {
    // ignore cleanup errors
  }
}
